### ISSUE TITLE
Segmentation fault with FIXT.1.1

### ISSUE THREAD

**Issue by dalmatine** [AquaQAnalytics/kdb-fix-adaptor#4]
Hi, any help would be **greatly appreciated**! I am getting a segmentation fault when trying to initiate a session using FIXT.1.1. The config used, stacktrace are below.

The acceptor and initiators start ok, but then upon the receipt of the first message from the initiator, the acceptor segfaults. Details below.

To recreate: 
In one q session start the acceptor: .fix.create[`acceptor;`:config.ini]
and in another initiator: .fix.create[`initiator;`:config.ini]
At this point the acceptor crashes upon the receipt of the open connection message.

## Versions
 release » 0.5.1
 quickfix » 1.14.3
 os » Linux
 arch » x86_64
 git commit »
 git commit datetime »
 build datetime » Tue 14 Jan 14:20:33 GMT 2020
 kdb compatibility » 3.x
 compiler flags »  -DBOOST_LOG_DYN_LINK -Wall -Werror -fno-strict-aliasing -std=c++11 -Os -DKXVER=3 -fpic

## Message that crashes the acceptror (which looks ok...)
8=FIXT.1.1
9=72
35=A
34=1
49=AQUAQ
52=20200114-14:59:38.753
56=BROKER
98=0
108=5
1137=9
10=167

## seg fault message
Sorry, this application or an associated library has encountered a fatal error and will exit.
If known, please email the steps to reproduce this error to tech@kx.com
with a copy of the kdb+ startup banner and the info printed below.
Thank you.
SIGSEGV: Fault address 0x10
q() [0x486cab]
/lib64/libpthread.so.0(+0xf630) [0x7f47ebc30630]
/lib64/libstdc++.so.6(_ZNSsC1ERKSs+0x18) [0x7f47e6d98cb8]
/home/kdb/src/kdb/fix_prev/kdbfix.0.5.1.so(+0x11709) [0x7f47e7318709]
/home/kdb/src/kdb/fix_prev/kdbfix.0.5.1.so(+0x11825) [0x7f47e7318825]
/home/kdb/src/kdb/fix_prev/kdbfix.0.5.1.so(_ZN20FixEngineApplication9fromAdminERKN3FIX7MessageERKNS0_9SessionIDE+0x9) [0x7f47e73188a3]
/usr/local/lib/libquickfix.so.17(_ZN3FIX7Session6verifyERKNS_7MessageEbb+0x22d) [0x7f47e702b63d]
/usr/local/lib/libquickfix.so.17(_ZN3FIX7Session9nextLogonERKNS_7MessageERKNS_12UtcTimeStampE+0xb29) [0x7f47e702f549]
/usr/local/lib/libquickfix.so.17(_ZN3FIX7Session4nextERKNS_7MessageERKNS_12UtcTimeStampEb+0xc75) [0x7f47e70309b5]
/usr/local/lib/libquickfix.so.17(_ZN3FIX7Session4nextERKSsRKNS_12UtcTimeStampEb+0x17e) [0x7f47e70326be]
/usr/local/lib/libquickfix.so.17(_ZN3FIX24ThreadedSocketConnection13processStreamEv+0x54) [0x7f47e70688e4]
/usr/local/lib/libquickfix.so.17(_ZN3FIX24ThreadedSocketConnection4readEv+0x151) [0x7f47e7068af1]
/usr/local/lib/libquickfix.so.17(_ZN3FIX22ThreadedSocketAcceptor22socketConnectionThreadEPv+0x20) [0x7f47e7060fc0]
/lib64/libpthread.so.0(+0x7ea5) [0x7f47ebc28ea5]
/lib64/libc.so.6(clone+0x6d) [0x7f47eb9518cd]
Segmentation fault

## config used
[DEFAULT]
BeginString=FIXT.1.1
ReconnectInterval=60
SocketAcceptPort=7091
SenderCompID=AQUAQ
TargetCompID=BROKER
TargetSubID=ADMIN
SocketNodelay=Y
PersistMessage=Y
FileStorePath=cache
FileLogPath=log
AppDataDictionary=/home/kdb/src/kdb/fix/spec/FIX50SP2.xml
TransportDataDictionary=/home/kdb/src/kdb/fix/spec/FIXT11.xml

[SESSION]
ConnectionType=acceptor
StartTime=00:30:00
EndTime=23:30:00
ReconnectInterval=30
HeartBtInt=5
SocketAcceptPort=7091
SocketReuseAddress=Y
AppDataDictionary=/home/kdb/src/kdb/fix/spec/FIX50SP2.xml
TransportDataDictionary=/home/kdb/src/kdb/fix/spec/FIXT11.xml
SenderCompID=BROKER
TargetCompID=AQUAQ
FileStorePath=cache
FileLogPath=log
DefaultApplVerID=9

[SESSION]
BeginString=FIXT.1.1
ConnectionType=initiator
StartTime=00:30:00
EndTime=23:30:00
ReconnectInterval=15
HeartBtInt=5
SocketConnectPort=7091
SocketConnectHost=127.0.0.1
AppDataDictionary=/home/kdb/src/kdb/fix/spec/FIX50SP2.xml
TransportDataDictionary=/home/kdb/src/kdb/fix/spec/FIXT11.xml
SenderCompID=AQUAQ
TargetCompID=BROKER
FileStorePath=cache
FileLogPath=log
DefaultApplVerID=9

**Comment by frenzy21** [comment]
Hi,

Could you please email support@aquaq.co.uk with this issue along with the version of kdb+ you are using. 

We would like to work through this issue and find out your exact use case.

James

**Comment by dalmatine** [comment]
Thank you very much for the fix!
